import asyncio
from enum import Enum

from . import ReqMessage, ResMessage

class Connection:
  def __init__(self) -> None: ...
  @property
  def connected(self) -> bool: ...
  @property
  def peername(self) -> tuple[str, int]: ...
  def send_request(self, msg: ReqMessage) -> asyncio.Future[ResMessage]: ...
  def send_response(self, orig_msg: ReqMessage, msg: ResMessage) -> None: ...
  def disconnect(self) -> asyncio.Future: ...
  async def on_connected(self) -> None: ...
  async def on_disconnected(self, exc: Exception) -> None: ...
  async def on_message(self, msg: ReqMessage) -> bool: ...
