import asyncio

from . import ReqMessage, Connection, SN

class Server:
  def __init__(self, loop: asyncio.AbstractEventLoop, port=10081) -> None: ...
  async def listen(self) -> None: ...
  async def on_connected(self, connection: ServerConnection) -> None: ...
  async def on_disconnected(self, connection: ServerConnection, exc: Exception) -> None: ...
  async def on_message(self, connection: ServerConnection, msg: ReqMessage) -> bool: ...

class ServerConnection(Connection):
  def __init__(self, server: Server):
    self.server = server
    self.sn : SN
